# Generated by Django 4.2.1 on 2023-07-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_author_profile_pic_alter_post_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.author'),
        ),
    ]
