# Generated by Django 4.2.1 on 2023-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('U', 'Up Vote'), ('D', 'Down Vote')], default='', max_length=1),
        ),
    ]
