# Generated by Django 4.2.1 on 2023-07-05 10:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vote_delete_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='defaults/default_profile_pic.jpg', force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 400], upload_to='authors'),
        ),
    ]
