# Generated by Django 3.2.7 on 2023-07-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_image_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
