# Generated by Django 3.2.7 on 2023-09-16 09:55

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=tinymce.models.HTMLField(default='none'),
        ),
    ]
