# Generated by Django 3.2.7 on 2023-09-16 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230916_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email format')]),
        ),
    ]
