# Generated by Django 3.2.7 on 2023-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='roles',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='User', max_length=50),
        ),
    ]
