# Generated by Django 3.2.7 on 2023-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_author_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='roles',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
